### ISSUE TITLE
Amnesia fails to compile with Elixir 1.0.5, Erlang 18

### ISSUE THREAD

**Issue by jfcloutier** [meh/amnesia#33]
== Compilation error on file lib/amnesia/event.ex ==
** (CompileError) lib/amnesia/event.ex:29: type record() undefined
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6

**Comment by meh** [comment]
Fixed on master.

**Comment by jfcloutier** [comment]
That was FAST! I don't think the ink had dried from my issue post. Thanks. --JF
