### ISSUE TITLE
Another issue with Elixir 1.7 - Kernel.Typespec.defines_type?/3 is undefined

### ISSUE THREAD

**Issue by dmilith** [meh/amnesia#83]
```
== Compilation error in file lib/data/model.ex ==
** (UndefinedFunctionError) function Kernel.Typespec.defines_type?/3 is undefined or private. Did you mean one of:

      * defines_type?/2

    (elixir) Kernel.Typespec.defines_type?(Model.RecordedScenario, :t, 0)
    lib/data/model.ex:17: (module)
    lib/data/model.ex:17: (module)
```

Happens in two of my projects after upgrading backend Elixir to 1.7.3.

My model.ex: https://github.com/VerKnowSys/Yst/blob/master/lib/data/model.ex

**Comment by dmilith** [comment]
After few clicks of investigation I've notices it's caused by this block of code:
https://github.com/meh/amnesia/blob/master/lib/amnesia/table/definition.ex#L938-L940

Is it safe to comment this thing out?

**Comment by dmilith** [comment]
Ok, did remove mix.lock, added this to mix.exs:

```
{:amnesia, github: "meh/amnesia", branch: "master", override: true},
{:exquisite, github: "meh/exquisite", branch: "master", override: true},
```

And problem solved! ;)
