### ISSUE TITLE
Amnesia does not compile with Elixir 0.14.3

### ISSUE THREAD

**Issue by atabary** [meh/amnesia#22]
I get this error with Elixir 0.14.3. Downgrading to 0.14.2 solves the issue.

```
= Compilation error on file lib/amnesia/metadata.ex ==
** (CompileError) lib/amnesia/metadata.ex:105: type t() undefined
    (stdlib) lists.erl:1336: :lists.foreach/2
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:170: :elixir.erl_eval/3
    (elixir) src/elixir.erl:158: :elixir.eval_forms/4
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
    (elixir) src/elixir.erl:170: :elixir.erl_eval/3
```

Full configuration: Elixir 0.14.3 and Erlang R17.1 on MacOS  X 10.9.4.
