### ISSUE TITLE
function to_binary/1 undefined

### ISSUE THREAD

**Issue by julienmarie** [meh/amnesia#7]
Hi,

It doesnt compile on the last elixir ( 0.10.3 ) :(

mix deps.compile amnesia
- Compiling amnesia
  Compiled lib/amnesia/counter.ex
  == Compilation error on file lib/amnesia.ex ==
  could not compile dependency amnesia, mix compile failed. If you want to recompile this dependency, please run: mix deps.compile amnesia
  *\* (CompileError) deps/amnesia/lib/amnesia.ex:66: function to_binary/1 undefined
  lists.erl:1323: :lists.foreach/2
  /private/tmp/elixir-1HDh/elixir-0.10.3/lib/elixir/lib/kernel/parallel_compiler.ex:82: Kernel.ParallelCompiler."-spawn_compilers/8-fun-0-"/3
